### ISSUE TITLE
Send udp packet failed

### ISSUE THREAD

**Issue by YumeMichi** [gityf/portalserver#1]
AC是信锐NAC-6200，在ubuntu上弄了下portal server，因为这个AC本身没带username、password等参数所以我自己改了一下其他的参数。
http://imgur.com/a/5gQHN

**Comment by mygityf** [comment]
可以贴一下日志文件
portalserver.log.info
portalserver.log.wf

初步定位是bras没有回复信息，或者是因为bras没有将请求的地址加入到白名单中。
